#%RAML 1.0 Library
usage: Datatypes Library

types:
  request: !include employeeRequest.raml
  response: !include employeeResponse.raml
  employeeRequest: !include employeesRequest.raml
  scoreResponse: !include employeeScore.raml